### ISSUE TITLE
variadic isPositive function

### ISSUE THREAD

**Issue by jhowardjr** [variadicjs/variadic.js#13]
Requesting help creating a variadic isPositive function that verifies all the numbers in the parameter list are positive.

**Comment by khusbuchandra** [comment]
isPositiveNumber function can verify all positive numbers greater than 0. I would suggest to have another variadic function to verify positive integers as they are quite different from just positive numbers

**Comment by ignacioxd** [comment]
@khusbuchandra that's a good idea. Maybe `isPositiveInt`?

**Comment by scottwestover** [comment]
@jhowardjr Can this issue be closed? In the libs folder there is a isPositiveNumber function. Is that for this issue, or is this for something different?

**Comment by scottwestover** [comment]
@ignacioxd @khusbuchandra I created a separate issue for the isPositiveInt function.
