### ISSUE TITLE
variadic isNegative function

### ISSUE THREAD

**Issue by jhowardjr** [variadicjs/variadic.js#14]
Requesting help creating a variadic isNegative function that verifies all the numbers in the parameter list are positive.

**Comment by scottwestover** [comment]
@jhowardjr Can this issue be closed? In the libs folder there is a isNegativeNumber function. Is that for this issue, or is this for something different?

**Comment by khusbuchandra** [comment]
@scottwestover Yes , isNegativeNumber() is for this issue, and we would also need a similar isNegativeInt function.

**Comment by scottwestover** [comment]
@khusbuchandra Thanks. I created a separate issue for that function. #45
