### ISSUE TITLE
variadic.js logo/graphics

### ISSUE THREAD

**Issue by jhowardjr** [variadicjs/variadic.js#16]
Help coming up with a variadic.js logo for the repo and the forthcoming demo page.

**Comment by khusbuchandra** [comment]
How about something which included V, [], and ... V made through brackets, I am just bouncing ideas, not a designer it can be something to start off with and build it from there. Any thoughts?

**Comment by jhowardjr** [comment]
Good idea! I like the idea of including the ellipses.

**Comment by jhowardjr** [comment]
If everyone sends examples of logos you like and any ideas I can send this over to a designer.

**Comment by jhowardjr** [comment]
Here are some of the GREAT logos @PepperAddict came up with: 

![page-open-animation-256](https://user-images.githubusercontent.com/1757435/35783054-a82e5fca-09cf-11e8-9978-ff38e69049f5.gif)

![dotjs-256](https://user-images.githubusercontent.com/1757435/35783058-aeefe0ae-09cf-11e8-8c17-a8dc84da6057.png)

![curly-w-dot](https://user-images.githubusercontent.com/1757435/35783062-b2512bf4-09cf-11e8-9849-e26d88b36b4c.png)

![nodot1080](https://user-images.githubusercontent.com/1757435/35783063-b527bf96-09cf-11e8-9fcc-dd620fb2af36.png)

![fade1024](https://user-images.githubusercontent.com/1757435/35783065-b7f2b8b6-09cf-11e8-9033-d672368d4ddf.png)

Which one are we going with?

**Comment by PepperAddict** [comment]
Hey @amr08 I was trying to line the dot with the J and I agree with you, that empty space on the left bugs me too. It's all vector so I can totally change it very easily if that's what you guys want. Just let me know and I can do it real quick.

**Comment by wolf2016** [comment]
I haven't even contributed code, but I like the 2nd and 3rd ones!

**Comment by wolf2016** [comment]
As for the space, maybe you could center the "JS" in the 3rd one.

**Comment by jhowardjr** [comment]
I think the third one is the winner! The JS is shifted to the side because it is based on the official JS logo, but if everyone agrees to it should be centered I'm good with it.
