### ISSUE TITLE
variadic variance() function

### ISSUE THREAD

**Issue by jmbothe** [variadicjs/variadic.js#30]
Requesting help creating a variadic variance() function that takes a series of numbers and returns the statistical variance of those numbers

**Comment by devNoiseConsulting** [comment]
I might as well do this one as well.

**Comment by devNoiseConsulting** [comment]
Ok have this done.

The standard deviation functions are have to calculate variance to get the answer. 
Q: Should they be updated to use the variance function or left as is?

**Comment by jmbothe** [comment]
@devNoiseConsulting yea, I would go ahead and use `variance()` in the standard deviation functions. That way you don't have to repeat yourself.

**Comment by devNoiseConsulting** [comment]
#41 closed this issue.
