### ISSUE TITLE
variadic standardDeviation() functions

### ISSUE THREAD

**Issue by jmbothe** [variadicjs/variadic.js#31]
Requesting help creating TWO variadic standard deviation functions:

1. a sampleStandardDeviation() function that takes a series of numbers and returns the sample SD of those numbers.

2. a populationStandardDeviation() function Requesting help creating a variadic average() function that takes a series of numbers and returns the population SD of those numbers.

**Comment by devNoiseConsulting** [comment]
I'd like to work on this one.

**Comment by jhowardjr** [comment]
@devNoiseConsulting it's all yours!

**Comment by devNoiseConsulting** [comment]
Question about writing the test spec. Since the result will be a floating point, I worry that result may not always be exactly the same. Is there a way to test against a rounded result?

**Comment by devNoiseConsulting** [comment]
Never mind, found the floatPrecise function and use it in my code.

**Comment by jmbothe** [comment]
Hi @devNoiseConsulting thanks for tackling this! Glad you found `floatPrecise()`. Just so you are aware, that function doesn't actually solve any of the underlying issues with floats. It just looks for a long run of zeros or nines at the end of a number and removes them.  So its more like a formatting tool than a reliable arithmetic tool. But for this library it is useful and acceptable way to handle floating point imprecision.

Happy coding!

**Comment by devNoiseConsulting** [comment]
#39 closed this issue.
