### ISSUE TITLE
Bug in ESLint Airbnb Standard affects this repo

### ISSUE THREAD

**Issue by jmbothe** [variadicjs/variadic.js#34]
Just a heads up to anyone who uses Visual Studio Code editor in Windows: learn from my suffering!

So here is the problem: One of the development dependencies, `eslint-config-airbnb-standard`, installs its own dependencies in its own `node_modules` directory deep in the projects main `node_modules` directory. Windows has a limit on on the maximum number of characters allowed in a file path: 260 characters. So the end result is that the dependencies of `"eslint-config-airbnb-standard` are unreachable by the VSCode ESLint plugin, and you get this error in VSCode:

`Error: Failed to load plugin: Cannot find module 'eslint-plugin-import'

Now, you COULD go to your command line and `npm install` that dependency manually, so that you get another copy in a shallower directory that is reachable by VSCode, but the problem is there are actually MANY dependencies that are unreachable, so once you install that dependency, you'll just get a new error for the next unreachable dependency.

The best thing I found to do is to run [`npm dedupe`](https://docs.npmjs.com/cli/dedupe). This lovely little command will flatten out your `node_modules` directory, making all of those dependencies accessible to VSCode.

It might be worth mentioning this in the docs, or consider switching to a different ESLint config, like [`eslint-config-airbnb-base`](https://www.npmjs.com/package/eslint-config-airbnb-base).

EDIT: It turns out that running `npm dedupe` is not as awesome as it sounds. It ended up causing some problems with this repo's test coverage package. So right now, the only way to handle this bug without causing problems elsewhere is to `npm install` all the unreachable dependencies manually. :(

**Comment by jmbothe** [comment]
I went ahead and opened an issue with [`eslint-config-airbnb-standard`](https://github.com/doasync/eslint-config-airbnb-standard/issues/2)

**Comment by ignacioxd** [comment]
Is this something that can be fixed by moving from `npm` to `yarn`?

**Comment by jhowardjr** [comment]
I don't see anything wrong with making the change as long as it's documented.

**Comment by jmbothe** [comment]
@ignacioxd I am not sure, but I guess the answer depends on where exactly the bug lies. As I see it, the problem is that the style guide's dependencies are being installed so deep in the directory tree. Is that `npm`'s problem, or a problem with the package? I don't really know. Further, if it weren't for the OTHER bug affecting `nyc` and `babel`, the `npm dedupe` command would be an acceptable fix to THIS bug.

So, yea, its complicated... haha. I'm def open to suggestions cuz I don't know a whole lot about this stuff, although as a windows user I am constantly running into problems like this...

**Comment by jhowardjr** [comment]
I've updated the .eslintrc to use airbnb-base, limited the linting to *.js, and added a .gitattributes file that prevents git from converting line breaks. @jmbothe if you get a change try pulling the repo and let me know if this fixes the issues on windows.

**Comment by jmbothe** [comment]
works like a charm now! I deleted `node_modules` and re-`npm install`ed, and all is good :) Thanks!

**Comment by jhowardjr** [comment]
Using ```airbnb-base``` seems to fix the issue.
