### ISSUE TITLE
variadic isNegativeInt Function

### ISSUE THREAD

**Issue by scottwestover** [variadicjs/variadic.js#45]
Verify that all integers are negative. 
Referenced from #14.

**Comment by khusbuchandra** [comment]
Can this be assigned to me?

**Comment by jhowardjr** [comment]
@khusbuchandra you'll to accept the invite I sent you so that I can assign the issue you.

**Comment by khusbuchandra** [comment]
Ahh! I had missed the mail and just now digged it out. Thanks @jhowardjr  👍

**Comment by khusbuchandra** [comment]
Function to verify negative integer is added.
