### ISSUE TITLE
Using private functions to avoid redundancy

### ISSUE THREAD

**Issue by tdnelson2** [variadicjs/variadic.js#64]
I'd like to add `isComposit` but after looking over the work @jmbothe did on `isPrime`, I realized I could reuse his `testPrime` function. @jmbothe is it cool if I move `testPrime` and it's dependency function to a new module called `_testPrime`? By doing so, `isComposit` would simply be:

```
const { _testPrime } = require('./_testPrime');

const handleErrors = (params) => { ... }; // truncated

const testComposit = (num) => {
  // num % 1 checks that num is an integer.
  // There are no prime or composit numbers less than 2, hence check for num < 2.
  if (num % 1 || num < 2) return false;
  return !_testPrime(num);
};

exports.isComposit = (...params) => {
  handleErrors(params);
  return params.every(testComposit);
};
```

**Comment by jhowardjr** [comment]
That should be ok.

**Comment by devNoiseConsulting** [comment]
I guess the questions is should @tdnelson2 refactor the testPrime function out of isPrime or should he just use isPrime? (ie `return !isPrime(num);`) The work I did on the standard deviation functions made use of other functions in the code base. The only reason I don't see for using isPrime is that the code may end up doing extra parameter checks. Thoughts

**Comment by jhowardjr** [comment]
@tdnelson2 @devNoiseConsulting is correct. ```isPrime``` provides some useful error handling around the ``testPrime``` function that you wouldn't need to repeat in ```isComposit```.

**Comment by tdnelson2** [comment]
Okay this is what I settled on. I'm going to go ahead and submit the PR.

```javascript
const { isPrime } = require('./isPrime');

// `isPrime` checks if the number is an integer greater than 1
// but since we simply want `isPrime` to check if this number
// is prime, we need to do the check again to avoid a false result.
const testComposit = num => (num % 1 || num < 2 ? false : !isPrime(num));

exports.isComposit = (...params) => {
  if (params.length === 0) throw new Error('Must provide one or more paramters');
  return params.every(testComposit);
};

```
